-- AgentX hosted persistence schema. Apply with goose/atlas or psql in a transaction.
-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, issuer text NOT NULL, subject text NOT NULL, email text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (issuer, subject));
CREATE TABLE IF NOT EXISTS workspaces (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memberships (workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('owner','admin','developer','viewer')), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (workspace_id, user_id));
CREATE TABLE IF NOT EXISTS packages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, name text NOT NULL, visibility text NOT NULL DEFAULT 'private', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (workspace_id, name));
CREATE TABLE IF NOT EXISTS releases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), package_id uuid NOT NULL REFERENCES packages(id) ON DELETE CASCADE, version text NOT NULL, sha256 text NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'published', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (package_id, version));
CREATE TABLE IF NOT EXISTS artifacts (release_id uuid PRIMARY KEY REFERENCES releases(id) ON DELETE CASCADE, bucket text NOT NULL DEFAULT 'local', object_key text NOT NULL, size_bytes bigint NOT NULL, content_type text NOT NULL DEFAULT 'application/octet-stream');
CREATE TABLE IF NOT EXISTS devices (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, name text NOT NULL, platform text, agent_versions_json jsonb NOT NULL DEFAULT '{}', last_seen_at timestamptz);
CREATE TABLE IF NOT EXISTS device_packages (device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE, name text NOT NULL, version text NOT NULL, sha256 text NOT NULL, observed_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(device_id, name));
CREATE TABLE IF NOT EXISTS policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, revision bigint NOT NULL, document_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id, revision));
CREATE TABLE IF NOT EXISTS manifests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, revision bigint NOT NULL, document_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(workspace_id, revision));
CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid REFERENCES workspaces(id) ON DELETE CASCADE, actor_id text, action text NOT NULL, resource_type text, resource_id text, metadata_json jsonb NOT NULL DEFAULT '{}', request_id text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS outbox (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), topic text NOT NULL, payload_json jsonb NOT NULL, attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, dead_lettered_at timestamptz, last_error text);
ALTER TABLE outbox ADD COLUMN IF NOT EXISTS dead_lettered_at timestamptz;
ALTER TABLE outbox ADD COLUMN IF NOT EXISTS last_error text;
CREATE TABLE IF NOT EXISTS idempotency_keys (workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, key text NOT NULL, resource_type text NOT NULL DEFAULT 'release', request_fingerprint text NOT NULL, response_json jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (workspace_id, key));
ALTER TABLE idempotency_keys ADD COLUMN IF NOT EXISTS request_fingerprint text NOT NULL DEFAULT '';
ALTER TABLE idempotency_keys ADD COLUMN IF NOT EXISTS resource_type text NOT NULL DEFAULT 'release';
CREATE INDEX IF NOT EXISTS audit_events_workspace_created_idx ON audit_events(workspace_id, created_at DESC);
